simple_social_clone/simplesocial/accounts/urls.py
from django.conf.urls import url
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    re_path(
        r"login/$",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    re_path(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    re_path(r"signup/$", views.SignUp.as_view(), name="signup"),
]

simple_social_clone/simplesocial/posts/urls.py
from django.conf.urls import re_path

from . import views

app_name = "posts"

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)", views.UserPosts.as_view(), name="for_user"),
    re_path(
        r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.PostDetail.as_view(),
        name="single",
    ),
    re_path(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(), name="delete"),
]

simple_social_clone/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import re_path, include
from . import views

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^accounts/", include("accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^test/$", views.TestPage.as_view(), name="test"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^posts/", include("posts.urls", namespace="posts")),
    re_path(r"^groups/", include("groups.urls", namespace="groups")),
]

simple_social_clone/simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Tea Heaven</title>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- Optional theme -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous"
    />
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}" />
  </head>
  <body>
    <nav
      class="navbar navbar-light"
      style="background-color: #D2F2C9;"
      role="navigation"
      id="navbar"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Tea Heaven</a>

        <ul class="nav justify-content-end">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'groups:create' %}"
              >Create Group</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}
      <!-- Block -->
      {% endblock %}
    </div>
  </body>
  <!-- <img
    src="https://images.unsplash.com/photo-1558160074-4d7d8bdf4256?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"
    class="img-fluid"
    alt="Responsive image"
  /> -->
  <script
    type="text/javascript"
    src="{% static 'simplesocial/js/master.js' %}"
  ></script>
</html>

simple_social_clone/simplesocial/templates/index.html
{% extends "base.html" %}
<!-- Block -->
{% block content %}
<h1>Welcome to Tea Heaven!</h1>
{% endblock %}

simple_social_clone/simplesocial/templates/test.html
{% extends "base.html" %}
<!-- BLOCK -->
{% block content %}
<h1>You are now logged in!</h1>

{% endblock %}

simple_social_clone/simplesocial/templates/thanks.html
{% extends "base.html" %}
<!-- BLOCK -->
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}